FROM rfdocker:3.0.4.rest

RUN apk add --update --no-cache curl unzip dbus-x11 ttf-freefont firefox-esr xvfb

ENV UNAME="robot" \
    GNAME="robot" \
    UHOME="/home/robot" \
    HOST_UID="1000" \
    HOST_GID="1000" \
    SHELL="/bin/bash"

RUN pip install --no-cache-dir selenium && \
	pip install --no-cache-dir pyvirtualdisplay

WORKDIR "$UHOME"

ENTRYPOINT ["entrypoint", "robot", "--outputdir", "results"]
